export const GET_POKEMONS = "GET_POKEMONS";
export const GET_POKEMON_DETAIL = "GET_POKEMON_DETAIL";
export const GET_TYPES = "GET_TYPES";
export const GET_BY_NAME ="GET_BY_NAME";

export const CREATE_POKEMON = "CREATE_POKEMON";